### ISSUE TITLE
Красивый формат меток

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SCP-Graphs#1]
Пока что в ТЗ формат меток максимально уродливый и почти дословно повторяющий внутреннюю кодировку суперкомпилятора MSCP-A. Это сделано намеренно, поскольку красивый вывод нам понадобится в двух формах. Первая --- это собственно рефальский формат. Вторая --- похожий на него, но несколько более привычный для любителей функциональных языков. Должен выбираться по ключу (по умолчанию - рефальский).

В рефал-формате кодировка в выходной язык происходит по-рабоче-крестьянски:

* `enc(par [Class] [Name])` -> `[Class].[Name]`;
* `enc(call [Name] (arg [Expr]))` -> `<[Name] enc([Expr])>`;
* `enc(assign [Param] ([Expr]))` -> `enc([Param]) -> enc([Expr])` для меток на входящих рёбрах графа;
* `enc(assign [Param] ([Expr]))` -> `enc([Param]) := enc([Expr])` для меток на обратных рёбрах графа и в `let`-конструкциях;
* `enc(('*' [Expr]))` -> `(enc([Expr]))`.

В TRS-формате (такое сокращение от term rewriting systems) кодировка чуть-чуть другая (три последних правила, для `assign` и структурных скобок --- те же самые):
* `enc(par [Class] [Name])` -> `[Class]([Name] в нижнем индексе)` -- используем тег `<SUB>`, который современной graphviz поддерживается;
* `enc(call [Name] (arg [Expr]))` -> `[Name](enc([Expr]))` --- здесь еще понадобится автоматически определять, когда от функции одного аргумента можно перейти к функции.

# Автоопределение местности функций в TRS-формате

Эта функция будет вылавливать только совсем-совсем прозрачные случаи, когда переход от одного аргумента к нескольким не повредит, а сделает красиво.

Определим псевдоаргументы следующим образом.
```
[PseudoArg] ::= ('*' [Expr])
```
Вызов функции разбивается на псевдоаргументы, если ее аргумент имеет одну из следующих двух форм.
```
[Multiarg] ::= [PseudoArg]+ | [PseudoArg]+ [Expr]`
```
Во втором случае последним псевдоаргументом считается выражение в общей форме, следующее за всеми предыдущими псевдоаргументами. В принципе, первый случай в правиле для `[Multiarg]` избыточный, но он иногда позволяет избавиться от лишних структурных скобок при отрисовке графа суперкомпиляции.

Если все вызовы функции `[FName]` во всём графе *всегда* разбиваются на одни и те же псевдоаргументы, в одном и том же количестве, то мы считаем себя вправе построить ее TRS-представление как функции нескольких аргументов. Количество аргументов определяется как максимум псевдоаргументов, гарантированно имеющийся в каждом вызове функции `[FName]`. При этом, если псевдоаргументы распознаются по образцу `[PseudoArg]+ [Expr]`, то `[Expr]` не должна быть пустым выражением хотя бы для одного вызова `[FName]`. 

**ПРИМЕРЫ**

Пусть в графе встречаются только следующие вызовы функции `F`:
* `(call F (arg ('*' A) (par e 22)(call G (arg A))))`
* `(call F (arg ('*' (par e 1001) ('*' A)) ))`
* `(call F (arg ('*')('*')))`

Тогда ее можно представить как функцию от двух аргументов, TRS-форма вызовов которой будет такая:
* `F(A, e22 G(A))`
* `F(e1001 (A), /* пусто */)`
* `F(/* пусто */, (/* пусто */))`

То есть вторым аргументом `F` служит весь хвост выражения после первых структурных скобок. Поэтому ориентироваться тупо на количество структурных скобок в самом внешнем уровне вложенности нельзя --- их количество может быть разным, но на количестве псевдоаргументов это может и не сказаться.

Второй пример будет отрицательным, из разряда "лучше перебдеть, чем недобдеть". Допустим, в графе есть такие вызовы функции `F`:
* `(call F (arg (call G (arg (par e x))) ('*' A)))`
* `(call F (arg ('*' (par e 434))))`

Их аргументы имеют общий вид --- в конце к ним приписано выражение в структурных скобках. Но псевдоаргументы здесь признаются отсутствующими, поскольку считываются только с начала.

Третий пример показывает, как можно сэкономить одни структурные скобки при считывании формата псевдоаргументов в форме [PseudoArg]+.

Рассмотрим вызовы `(call F (arg ('*' A)('*' B)('*' C)))` и `(call F (arg ('*' (par e 1))('*' (par e 1))('*' (par e 1))))`. Сколько у них псевдоаргументов? Если бы условия, что `[Expr]` не пусто, не было, мы могли бы сказать, что аргумента может быть четыре: три первые скобки и четвертый, следующий за ними в свободной форме. Однако здесь так не получится. Поэтому, скажем, в первом случае `[Expr]` может сопоставляться только с `('*' C)` либо с `('*' B)('*' C)` --- порождая описание для трех или двух псевдоаргументов, соответственно. Поскольку во втором случае тоже есть три структурные скобки, и тоже получается либо три, либо два псевдоаргумента, правильным форматом назначается максимум: формат из трех псевдоаргументов. Если воспользоваться образцом `[PseudoArg]+`, тоже получается три псевдоаргумента. 

В первом случае результатом TRS-кодировки будут выражения `F(A, B, (C))` и `F(e1, e1, (e1))`. Не очень-то красиво, что последний аргумент в скобках, которые здесь не несут никакой смысловой нагрузки. При использовании `[PseudoArg]+`-образца TRS-кодировками будут `F(A, B, C)` и `F(e1, e1, e1)`  --- более приятные для глаза. Поэтому, если удается построить разбиение на псевдоаргументы с помощью `[PseudoArg]+`-образца, надо им всегда пользоваться.
 
Ответственной за реализацию поиска формата в псевдоаргументах назначается @pirosveta. Базовая перекодировка в рефал-представление и в TRS-представление простенькая, ее можно сделать быстро после завершения лексера, поэтому раз @2wendex2 взял на себя этот этап работы, он может его и завершить. Повторяю, от первого этапа (как я понимаю, его выполняет @2wendex2 ) никакой красоты представления не требуется --- тупо парсер, лексер и первый вариант dot-описания.

**Comment by Mazdaywik** [comment]
Немножко поправил разметку.

**Comment by TonitaN** [comment]
@pirosveta, @VolkovNik , правильно ли я увидела, что сейчас актуальной веткой является `label-format`? Просьба написать в `readme`, по каким ключам можно посмотреть `trs` и `refal`-представление, а то пока что я вижу представление только во внутреннем языке суперкомпилятора.
Ещё по мелочи (возможно, эти мелочи уже исправлены, если запускать по ключу?):
* нет обратных рёбер;
* если сохраняется статус, то скобки точно лишние, а вообще, статус сохранять в узле не надо, его можно отмечать только с помощью изменения формата отрисовки (например, изменяя форму обрамления узла --- это к задаче @VolkovNik );
* метки в виде `()` (пустых скобок) в графе не нужны.

**Comment by Mazdaywik** [comment]
> @pirosveta, @VolkovNik , правильно ли я увидела, что сейчас актуальной веткой является `label-format`?

Эта рабочая ветка в процессе работы. Когда она будет относительно доведена до ума, они откроют pull request в `main`. К такому стилю работы они привыкли на УТП/ПТП.

Хотя я не знаю, как ты настраивала репозиторий — можно ли у тебя непосредственно коммитить в `main` или нет.

**Comment by TonitaN** [comment]
@pirosveta , вы молодец, закрываю заявку.
