### ISSUE TITLE
Юнит-тесты

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SCP-Graphs#3]
Просьба не забывать про юнит-тестирование. В частности, @2wendex2 нужно учесть ошибочные тесты на зацикливание в несуществующий узел и на повторные имена разных узлов в графе. Семантическая часть суперкомпиляции, как то: проверка, чтобы присваивания содержали имена параметров, входящие в конфигурации узлов, и т.д. ---  уже не ваша задача, здесь полагаемся на совесть разработчика суперкомпилятора.

**Comment by 2wendex2** [comment]
Сделал

**Comment by TonitaN** [comment]
@2wendex2 (к @VolkovNik  и @pirosveta это тоже относится), желательно указывать номер заявки при коммите, если коммит относится к конкретной заявке.
