### ISSUE TITLE
Правки в dot-представлении

### ISSUE THREAD

**Issue by TonitaN** [bmstu-iu9/SCP-Graphs#5]
@VolkovNik , в актуальной версии есть всё та же проблема с обратными рёбрами (их нет из looped-узлов, а должны быть, если написано: `looped to [Имя]`, значит, строим ребро из данного узла в узел [Имя]) и есть лишние скобки. В принципе, имя узла не нужно для внешнего представления графа (оно нужно только для описания dot-формата). Если его выкинуть, тогда можно избавиться от первой строчки в метке узла и от слова `NodeData` во второй. Также в `NodeData` первый элемент (в первых скобках) отрисовывать не надо, это рестрикции, и они в рамках этой практики остаются внутренними данными суперкомпиляции. И самые внешние скобки в `NodeData` тоже не нужны. 

Подстановка, описанная в узле, относится к ребру, входящему в узел из родительского. Например, в первом тесте (`test_1.scpgraph`) у корня должны быть три потомка (как и есть у вас), рёбра в которые из корня помечены все разными подстановками (а вот из них осталась одна, причём переехала на уровень ниже и там ещё и размножилась). А именно должны быть ветки: `e.N -> пусто`; `e.N -> I e.1`; `e.N -> S e.2`.

Везде, где идёт перекодировка `(assign [Par] ([Expr]))`, у вас сохранились круглые скобки вокруг `[Expr]` и вокруг всего списка подстановок, а они лишние (это наследие внутренней кодировки рефала). Кроме того, если очередная подстановка не переносится на следующую строку, то её обязательно надо отделить от предшествующей, например, точкой с запятой.

Таким образом, вместо `(e.x -> (e.y) t.z -> A)` надо отрисовывать `e.x -> e.y; t.z -> A`.

`Let`-узлы принято оформлять иначе, чем все прочие (другая форма рамки, например), и не хватает слова `Let` перед присваиваниями в `let`-узле. Правые части присваиваний в `let`-узле скобками выделять не надо, выражение после `in` скобками выделять не надо (всё это артефакты рефала), соседние присваивания надо разделять точкой с запятой.

По мелочи:
- -&gt; лучше заменить на &rarr; ;
- нужно ввести нормальное обозначение вместо пустых скобок для пустого слова, хорошо подойдёт греческая &epsilon; .

**Comment by VolkovNik** [comment]
@TonitaN, есть проблема в тестовых данных с обратными ребрами, кажется, они не соответствуют данной нам грамматике, поэтому парсер засовывает `Looped to` в `NodeData`

**Comment by TonitaN** [comment]
@VolkovNik , увидела, спасибо! Исправила декодер, могу выслать набор обновлённых тестов либо сам декодер+суперкомпилятор, чтобы вы их могли генерировать сами.

**Comment by VolkovNik** [comment]
@TonitaN, можете пожалуйста выслать набор обновлённых тестов ?

**Comment by TonitaN** [comment]
@VolkovNik , готово. Ещё раз спасибо за указанный баг!

**Comment by TonitaN** [comment]
@pirosveta , похоже, в последней версии сломалось экранирование угловых скобок в рефал-формате тегами `&lt;` и `&gt;` --- они правильно записываются в `dot`, но ломают граф при попытке их чтения, и не экранируются также символы стрелки и пустого слова, поэтому записываются в `dot` виде вопросительных знаков.

**Comment by Mazdaywik** [comment]
Не, ну прикольный ник у Пиросветы — свет от пиротехники.

![Бенгальский огонь (картинка из Викисклада)](https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Sparkler.JPG/640px-Sparkler.JPG)

@pirosveta, у Вас классный ник! 👍

**Comment by TonitaN** [comment]
Ещё есть неэкранированные бэкслэши в кавычках. Проверяйте, пожалуйста, dot-представление, например, через `dot -Tpng`, чтобы юникод отображался как следует.

**Comment by Mazdaywik** [comment]
Экранировать их можно как `\` → `_b`, например.

**Comment by TonitaN** [comment]
@pirosveta , всё здорово, закрываю заявку!
Два мелких момента:
- выделять скобками формулу после "in" в let-выражении тоже не нужно;
- если на ребре пустая метка (именно совсем пустая, без подстановок), то &epsilon; лучше на ней не ставить - пусть так и будет пустой.
